/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ff716c",
        "on-tertiary-fixed-variant": "#006742",
        "surface-tint": "#8ff5ff",
        "inverse-on-surface": "#52555c",
        "on-error-container": "#ffa8a3",
        "secondary-fixed-dim": "#ceb9ff",
        "tertiary-fixed-dim": "#00efa0",
        "secondary": "#ac89ff",
        "surface-container-lowest": "#000000",
        "background": "#0b0e14",
        "primary-fixed-dim": "#00deec",
        "on-secondary-fixed": "#41009a",
        "on-surface-variant": "#a9abb3",
        "tertiary": "#afffd1",
        "inverse-primary": "#006a71",
        "on-secondary-fixed-variant": "#6300e2",
        "on-secondary": "#290067",
        "on-tertiary-fixed": "#00472d",
        "surface-container": "#161a21",
        "on-background": "#ecedf6",
        "outline": "#73757d",
        "secondary-dim": "#874cff",
        "primary-container": "#00eefc",
        "secondary-container": "#7000ff",
        "on-primary": "#005d63",
        "surface-container-high": "#1c2028",
        "on-tertiary-container": "#005c3b",
        "surface-dim": "#0b0e14",
        "on-primary-fixed-variant": "#005e64",
        "tertiary-dim": "#00efa0",
        "primary-dim": "#00deec",
        "error-dim": "#d7383b",
        "error-container": "#9f0519",
        "surface-bright": "#282c36",
        "on-secondary-container": "#f8f1ff",
        "outline-variant": "#45484f",
        "surface": "#0b0e14",
        "inverse-surface": "#f9f9ff",
        "primary-fixed": "#00eefc",
        "secondary-fixed": "#dac9ff",
        "surface-container-low": "#10131a",
        "primary": "#8ff5ff",
        "surface-variant": "#22262f",
        "surface-container-highest": "#22262f",
        "on-tertiary": "#006642",
        "on-error": "#490006",
        "tertiary-fixed": "#00ffab",
        "on-surface": "#ecedf6",
        "tertiary-container": "#00ffab",
        "on-primary-container": "#005359",
        "on-primary-fixed": "#003f43"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms')
  ],
}
